import Head from "next/head";
import Image from "next/image";
import Picture from "../assets/wallhaven.jpg";
import Picture2 from "../assets/wallhaven-2.png";
import Books from "../assets/books.jpg";
import Child from "../assets/child.jpg"
import Dunes from "../assets/dunes.jpg"
import Elephants from "../assets/elephants.jpg"
import Fern from "../assets/fern.jpg"
import Flower from "../assets/flower.jpg"
import Girl from "../assets/girl.jpg"
import Mountain from "../assets/mountain.jpg"
import Mountains from "../assets/mountains.jpg"
import Ocean from "../assets/ocean.jpg"
import Street from "../assets/street.jpg"
import Winter from "../assets/winter.jpg"
import Footer from "@/components/footer";
import Header from "@/components/header";



export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />

      <main>
          
          <div className="mainGrid">
            <div className="card">
              <Image src={Books} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>
                  "Neque porro quisquam est qui dolorem ipsum quia dolor sit
                  amet, consectetur, adipisci velit..."
                </p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Child} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>sdfsdafcasdfcasdcvbnnnnnn sdfg da dsfg sdf gsdf </p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Dunes} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>Description</p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Elephants} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>Description</p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Fern} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>
                  "Neque porro quisquam est qui dolorem ipsum quia dolor sit
                  amet, consectetur, adipisci velit..."
                </p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Street} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>sdfsdafcasdfcasdcvbnnnnnn sdfg da dsfg sdf gsdf </p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Flower} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>Description</p>
                <span>Author</span>
              </content>
            </div>
            <div className="card">
              <Image src={Girl} className="thumbnail" />

              <content>
                <h1>Some title</h1>
                <p>Description</p>
                <span>Author</span>
              </content>
            </div>
          </div>
          {/* Main grid */}

        
      </main>
      <Footer />

    </>
  );
}
